org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.07

minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1)
neo_version=21.0.78-beta
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

mod_id=well
mod_name=Well Mod
mod_license=Apache License 2.0
mod_version=1.0.0
mod_group_id=cubicoder
mod_authors=cubicoder
mod_description=Adds a configurable well block for pumping fluids!

jei_version=19.3.1.25
# project id 245211; version 12.0.3
top_fileid=5502323
# project id 324717; version 15.1.3
jade_fileid=5493270
# project id 459701; version 1.10.1
catalogue_fileid=5441227
# project id 457570; version 2.5.0
configured_fileid=5441232
