modLoader="javafml"
loaderVersion="[45,)"
license="Apache License 2.0"
issueTrackerURL="https://github.com/cubicoder/Well-Mod/issues"

[[mods]]
modId="well"
version="${file.jarVersion}"
displayName="Well Mod"
updateJSONURL="https://raw.githubusercontent.com/cubicoder/Versions/main/well-update.json"
displayURL="https://github.com/cubicoder/Well-Mod"
itemIcon="well:well"
logoFile="well_logo.png"
credits="foreck and jbredwards for original idea"
authors="cubicoder"
description='''
Adds a well block for pumping water!
'''

[[dependencies.well]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.well]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
